name: Deploy Release to Bunny.net

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: codeberg-medium
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Dictionary Validation
        run: npm test

      - name: Build and Push Docker Image
        uses: https://codeberg.org/umglurf/buildah-action@main
        with:
          cache: true
          cache_repo: codeberg.org/${{ github.repository }}/cache
          container_file: ./Dockerfile
          credentials: |
            codeberg.org=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
            docker.io=${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}
          destinations: |
            codeberg.org/${{ github.repository }}:${{ github.ref_name }}
            codeberg.org/${{ github.repository }}:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/clearload:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/clearload:latest
          push: true
