name: Deploy Release to Bunny.net

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: codeberg-medium
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Dictionary Validation
        run: npm test

      - name: Install Buildah
        run: apt-get update && apt-get install buildah ca-certificates -y

      - name: Build and Push Versioned Tag
        uses: https://codeberg.org/actions/buildah-simple@main
        with:
          tag: "codeberg.org/${{ github.repository_owner }}/clearload:${{ github.ref_name }}"
          context: .
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: codeberg.org

      - name: Build and Push Latest Tag
        uses: https://codeberg.org/actions/buildah-simple@main
        with:
          tag: "codeberg.org/${{ github.repository_owner }}/clearload:latest"
          context: .
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: codeberg.org
